---

- name: Download Sophos
  shell: |
    curl -o /tmp/SophosSetup.sh https://api-cloudstation-us-east-2.prod.hydra.sophos.com/api/download/9e050a97bb5eed01eb80029cd3a6ef33/SophosSetup.sh

- name: Install Sophos
  shell: |
    chmod +x /tmp/SophosSetup.sh && /bin/bash /tmp/SophosSetup.sh --group=aws_servers